import Prism from "prismjs";

export const languages: {
  [name: string]: {
    grammar: Prism.Grammar;
    language: string;
  };
} = {
  Plaintext: { grammar: Prism.languages.text, language: "" },
  HTML: { grammar: Prism.languages.html, language: "html" },
  CSS: { grammar: Prism.languages.css, language: "css" },
  Javascript: { grammar: Prism.languages.js, language: "js" },
  AppleScript: { grammar: Prism.languages.applescript, language: "applescipt" },
  Bash: { grammar: Prism.languages.shell, language: "shell" },
  BASIC: { grammar: Prism.languages.basic, language: "basic" },
  Brainfuck: { grammar: Prism.languages.brainfuck, language: "brainfuck" },
  C: { grammar: Prism.languages.c, language: "c" },
  "C#": { grammar: Prism.languages.cs, language: "cs" },
  "C++": { grammar: Prism.languages.cpp, language: "cpp" },
  CoffeeScript: { grammar: Prism.languages.coffee, language: "coffee" },
  D: { grammar: Prism.languages.d, language: "d" },
  Dart: { grammar: Prism.languages.dart, language: "dart" },
  Docker: { grammar: Prism.languages.docker, language: "docker" },
  Erlang: { grammar: Prism.languages.erlang, language: "erlang" },
  Fortran: { grammar: Prism.languages.fortran, language: "fortran" },
  Go: { grammar: Prism.languages.go, language: "go" },
  GraphQL: { grammar: Prism.languages.graphql, language: "graphql" },
  Groovy: { grammar: Prism.languages.groovy, language: "groovy" },
  Haskell: { grammar: Prism.languages.hs, language: "hs" },
  HLSL: { grammar: Prism.languages.hlsl, language: "hlsl" },
  Java: { grammar: Prism.languages.java, language: "java" },
  JSON: { grammar: Prism.languages.json, language: "json" },
  Julia: { grammar: Prism.languages.julia, language: "julia" },
  Kotlin: { grammar: Prism.languages.kt, language: "kt" },
  LaTeX: { grammar: Prism.languages.tex, language: "tex" },
  Less: { grammar: Prism.languages.less, language: "less" },
  Lisp: { grammar: Prism.languages.lisp, language: "lisp" },
  Lua: { grammar: Prism.languages.lua, language: "lua" },
  Makefile: { grammar: Prism.languages.makefile, language: "makefile" },
  Markdown: { grammar: Prism.languages.md, language: "md" },
  Matlab: { grammar: Prism.languages.matlab, language: "matlab" },
  "Objective-C": { grammar: Prism.languages.objc, language: "objc" },
  Pascal: { grammar: Prism.languages.pascal, language: "pascal" },
  Perl: { grammar: Prism.languages.perl, language: "perl" },
  PHP: { grammar: Prism.languages.php, language: "php" },
  PowerShell: { grammar: Prism.languages.powershell, language: "powershell" },
  Python: { grammar: Prism.languages.python, language: "python" },
  R: { grammar: Prism.languages.r, language: "r" },
  Ruby: { grammar: Prism.languages.rb, language: "rb" },
  Rust: { grammar: Prism.languages.rust, language: "rust" },
  Sass: { grammar: Prism.languages.sass, language: "sass" },
  Scala: { grammar: Prism.languages.scala, language: "scala" },
  SQL: { grammar: Prism.languages.sql, language: "sql" },
  Swift: { grammar: Prism.languages.swift, language: "swift" },
  TOML: { grammar: Prism.languages.toml, language: "toml" },
  TypeScript: { grammar: Prism.languages.ts, language: "ts" },
  "Visual Basic": { grammar: Prism.languages.vb, language: "vb" },
  WebAssembly: { grammar: Prism.languages.wasm, language: "wasm" },
  XML: { grammar: Prism.languages.xml, language: "xml" },
  YAML: { grammar: Prism.languages.yml, language: "yml" }
};
